/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room-4.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room-4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Clock.geometry} material={nodes.Clock.material} position={[-3.966, 3.98, -1.421]} rotation={[0, -0.77, 0]} scale={1.224}>
        <mesh geometry={nodes.hours.geometry} material={nodes.hours.material} />
        <mesh geometry={nodes.minutes.geometry} material={nodes.minutes.material} />
        <mesh geometry={nodes.secondes.geometry} material={nodes.secondes.material} />
      </mesh>
      <mesh geometry={nodes.Plane051.geometry} material={nodes.Plane051.material} position={[-0.59, 1.83, 2.992]} scale={1.201} />
      <mesh geometry={nodes.Plane050.geometry} material={nodes.Plane050.material} position={[-0.589, 1.828, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane049.geometry} material={nodes.Plane049.material} position={[-0.588, 1.824, 2.997]} scale={1.201} />
      <mesh geometry={nodes.Plane048.geometry} material={nodes.Plane048.material} position={[-0.585, 1.831, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane047.geometry} material={nodes.Plane047.material} position={[-0.588, 1.827, 2.99]} scale={1.201} />
      <mesh geometry={nodes.Plane046.geometry} material={nodes.Plane046.material} position={[-0.585, 1.833, 2.992]} scale={1.201} />
      <mesh geometry={nodes.Plane045.geometry} material={nodes.Plane045.material} position={[-0.587, 1.824, 2.997]} scale={1.201} />
      <mesh geometry={nodes.Plane044.geometry} material={nodes.Plane044.material} position={[-0.588, 1.834, 2.99]} scale={1.201} />
      <mesh geometry={nodes.Plane043.geometry} material={nodes.Plane043.material} position={[-0.587, 1.826, 2.996]} scale={1.201} />
      <mesh geometry={nodes.Plane042.geometry} material={nodes.Plane042.material} position={[-0.589, 1.83, 2.992]} scale={1.201} />
      <mesh geometry={nodes.Plane041.geometry} material={nodes.Plane041.material} position={[-0.588, 1.826, 2.995]} scale={1.201} />
      <mesh geometry={nodes.Plane040.geometry} material={nodes.Plane040.material} position={[-0.588, 1.834, 2.989]} scale={1.201} />
      <mesh geometry={nodes.Plane039.geometry} material={nodes.Plane039.material} position={[-0.591, 1.825, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane038.geometry} material={nodes.Plane038.material} position={[-0.587, 1.833, 2.99]} scale={1.201} />
      <mesh geometry={nodes.Plane037.geometry} material={nodes.Plane037.material} position={[-0.589, 1.823, 2.996]} scale={1.201} />
      <mesh geometry={nodes.Plane036.geometry} material={nodes.Plane036.material} position={[-0.59, 1.826, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane035.geometry} material={nodes.Plane035.material} position={[-0.589, 1.827, 2.993]} scale={1.201} />
      <mesh geometry={nodes.Plane034.geometry} material={nodes.Plane034.material} position={[-0.587, 1.825, 2.995]} scale={1.201} />
      <mesh geometry={nodes.Plane033.geometry} material={nodes.Plane033.material} position={[-0.586, 1.831, 2.992]} scale={1.201} />
      <mesh geometry={nodes.Plane032.geometry} material={nodes.Plane032.material} position={[-0.588, 1.83, 2.991]} scale={1.201} />
      <mesh geometry={nodes.Plane031.geometry} material={nodes.Plane031.material} position={[-0.587, 1.828, 2.993]} scale={1.201} />
      <mesh geometry={nodes.Plane030.geometry} material={nodes.Plane030.material} position={[-0.589, 1.825, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane029.geometry} material={nodes.Plane029.material} position={[-0.59, 1.823, 2.995]} scale={1.201} />
      <mesh geometry={nodes.Plane028.geometry} material={nodes.Plane028.material} position={[-0.585, 1.828, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane027.geometry} material={nodes.Plane027.material} position={[-0.588, 1.822, 2.996]} scale={1.201} />
      <mesh geometry={nodes.Plane026.geometry} material={nodes.Plane026.material} position={[-0.586, 1.826, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane025.geometry} material={nodes.Plane025.material} position={[-0.588, 1.826, 2.993]} scale={1.201} />
      <mesh geometry={nodes.Plane024.geometry} material={nodes.Plane024.material} position={[-0.59, 1.824, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane023.geometry} material={nodes.Plane023.material} position={[-0.586, 1.826, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane022.geometry} material={nodes.Plane022.material} position={[-0.587, 1.826, 2.993]} scale={1.201} />
      <mesh geometry={nodes.Plane021.geometry} material={nodes.Plane021.material} position={[-0.587, 1.821, 2.996]} scale={1.201} />
      <mesh geometry={nodes.Plane020.geometry} material={nodes.Plane020.material} position={[-0.587, 1.821, 2.996]} scale={1.201} />
      <mesh geometry={nodes.Plane019.geometry} material={nodes.Plane019.material} position={[-0.584, 1.828, 2.993]} scale={1.201} />
      <mesh geometry={nodes.Plane018.geometry} material={nodes.Plane018.material} position={[-0.587, 1.823, 2.995]} scale={1.201} />
      <mesh geometry={nodes.Plane017.geometry} material={nodes.Plane017.material} position={[-0.588, 1.82, 2.997]} scale={1.201} />
      <mesh geometry={nodes.Plane016.geometry} material={nodes.Plane016.material} position={[-0.59, 1.82, 2.995]} scale={1.201} />
      <mesh geometry={nodes.Plane015.geometry} material={nodes.Plane015.material} position={[-0.588, 1.828, 2.991]} scale={1.201} />
      <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} position={[-0.587, 1.827, 2.992]} scale={1.201} />
      <mesh geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} position={[-0.589, 1.825, 2.992]} scale={1.201} />
      <mesh geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} position={[-0.59, 1.82, 2.995]} scale={1.201} />
      <mesh geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} position={[-0.59, 1.82, 2.994]} scale={1.201} />
      <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} position={[-0.585, 1.823, 2.995]} scale={1.201} />
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[-0.587, 1.82, 2.996]} scale={1.201} />
      <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} position={[-0.587, 1.829, 2.99]} scale={1.201} />
      <mesh geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} position={[-0.586, 1.826, 2.992]} scale={1.201} />
      <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[-0.585, 1.827, 2.992]} scale={1.201} />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[-0.589, 1.819, 2.995]} scale={1.201} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[-0.589, 1.825, 2.991]} scale={1.201} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-0.587, 1.82, 2.995]} scale={1.201} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-0.588, 1.827, 2.99]} scale={1.201} />
      <mesh geometry={nodes.schrodinger.geometry} material={nodes.schrodinger.material} position={[-0.299, 1.898, 2.997]} rotation={[0, -0.469, 0]} />
      <mesh geometry={nodes['coffe-smoke'].geometry} material={nodes['coffe-smoke'].material} position={[-0.312, 1.972, 2.997]} rotation={[0, -0.486, 0]} />
      <mesh geometry={nodes['photo-7'].geometry} material={nodes['photo-7'].material} position={[-2.14, 3.333, -3.241]} />
      <mesh geometry={nodes['photo-6'].geometry} material={nodes['photo-6'].material} position={[-1.709, 3.488, -3.676]} />
      <mesh geometry={nodes['photo-1'].geometry} material={nodes['photo-1'].material} position={[-2.54, 4.163, -2.825]} />
      <mesh geometry={nodes['photo-8'].geometry} material={nodes['photo-8'].material} position={[-2.501, 3.578, -2.871]} />
      <mesh geometry={nodes['photo-4'].geometry} material={nodes['photo-4'].material} position={[-1.619, 4.157, -3.767]} />
      <mesh geometry={nodes['photo-5'].geometry} material={nodes['photo-5'].material} position={[-1.306, 3.661, -4.094]} />
      <mesh geometry={nodes['photo-2'].geometry} material={nodes['photo-2'].material} position={[-2.092, 3.854, -3.287]} />
      <mesh geometry={nodes['photo-3'].geometry} material={nodes['photo-3'].material} position={[-2.095, 4.372, -3.29]} />
    </group>
  )
}

useGLTF.preload('/room-4.glb')
